### ISSUE TITLE
No module named 'diff_gaussian_rasterization.scene'

### ISSUE THREAD

**Issue by missTL** [fzhiheng/RoGS#10]
The following error is reported after I have installed the environment, how can I solve it?
![image](https://github.com/user-attachments/assets/2842dad1-b008-4c56-bb3e-93599d2ec88c)
pip list:
![image](https://github.com/user-attachments/assets/d2788fc3-462e-4c16-ad8f-678018b1b2da)

**Comment by missTL** [comment]
Could you please provide the Docker image for RoGS?

**Comment by MartinEthier** [comment]
@missTL I am running into the same issue. How did you solve it?

**Comment by githubwys** [comment]
hi，how can we deal with it？
