### ISSUE TITLE
How to produce nusc ground truth?

### ISSUE THREAD

**Issue by wadefrank** [fzhiheng/RoGS#2]
I run the code you provide as your advise to produce nusc ground truth:

`python -m preprocess.process --nusc_root /data/nuScenes/v1.0-mini/nuscenes/v1.0-mini --seg_root /data/RoGS/nuScenes_clip  ---save_root /data/RoGS/ -v mini --scene_names scene-0655`

but have output below:

`/home/qxit-ln-002408/anaconda3/envs/rogs/bin/python: No module named preprocess.process`

what should I do now?

**Comment by fzhiheng** [comment]
I misspelled the name of the script that needs to be run, please change `preprocess.process` to `preprocess.process_nusc.`

**Comment by wadefrank** [comment]
thank you for your reply, now I meet another problem, when I run:

`python train.py --config configs/local_kitti.yaml`

output:

`raceback (most recent call last):
  File "train.py", line 30, in <module>
    from utils.render import render, render_label
  File "/home/qxit-ln-002408/fx/Codes/3DGS/RoGS/utils/render.py", line 6, in <module>
    from diff_gs_label import GaussianRasterizationSettings as GaussianRasterizationSettingsLabel
ModuleNotFoundError: No module named 'diff_gs_label'`

how can I fix this problem?

**Comment by wadefrank** [comment]
Here is my directory tree:

`(rogs) ➜  RoGS git:(main) ✗ tree -L 2
.
├── configs
│   ├── local_kitti.yaml
│   ├── local_nusc_mini.yaml
│   └── local_nusc.yaml
├── datasets
│   ├── base.py
│   ├── kitti.py
│   ├── nusc.py
│   └── __pycache__
├── diff-gs-depth-alpha
│   ├── build
│   ├── CMakeLists.txt
│   ├── cuda_rasterizer
│   ├── diff_gaussian_rasterization
│   ├── diff_gaussian_rasterization.egg-info
│   ├── dist
│   ├── ext.cpp
│   ├── LICENSE.md
│   ├── rasterize_points.cu
│   ├── rasterize_points.h
│   ├── README.md
│   ├── setup.py
│   └── third_party
├── diff-gs-label
│   ├── build
│   ├── CMakeLists.txt
│   ├── cuda_rasterizer
│   ├── diff-gs-label
│   ├── diff_gs_label2.egg-info
│   ├── diff_gs_label.egg-info
│   ├── dist
│   ├── ext.cpp
│   ├── LICENSE.md
│   ├── rasterize_points.cu
│   ├── rasterize_points.h
│   ├── README.md
│   ├── setup.py
│   └── third_party
├── docs
│   └── image
├── eval.py
├── LICENSE
├── models
│   ├── exposure_model.py
│   ├── gaussian_model.py
│   ├── loss.py
│   ├── pose_model.py
│   └── road.py
├── preprocess
│   ├── process_nusc.py
│   └── __pycache__
├── README.md
├── train.py
└── utils
    ├── general_utils.py
    ├── image.py
    ├── logging.py
    ├── metrics.py
    ├── __pycache__
    ├── render.py
    ├── sh_utils.py
    ├── vis.py
    └── visualizer.py`

**Comment by wadefrank** [comment]
I find the reason, when I rename "diff-gs-label" to "diff_gs_label", and rerun "python setup.py install", and then I can run `python train.py --config configs/local_kitti.yaml` successfully.

**Comment by wadefrank** [comment]
Another question, how to visualize the result?

**Comment by fzhiheng** [comment]
> Another question, how to visualize the result?

The results will be automatically saved in the `output` folder.
