### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/kitti/Kitti/sequences/00/calib/000000.txt'

### ISSUE THREAD

**Issue by wadefrank** [fzhiheng/RoGS#3]
Where can I download Kitti/sequences/00/calib/000000.txt?

**Comment by fzhiheng** [comment]
https://s3.eu-central-1.amazonaws.com/avg-kitti/data_odometry_poses.zip

**Comment by wolf943134497** [comment]
@fzhiheng  Thanks for your amazing work!
The above link is not a download link for Kitti/sequences/00/calib/000000.txt. I find the calib file in /KITTI/training/calib/000000.txt， but when use the calib file，I can not get right results for "camera2world_all", and the python train.py running error.
I can run success for nuscene dataset.

can you give some advice about kitti odometry calib file?  @wadefrank @fzhiheng  Thanks
