### ISSUE TITLE
about kitti odometry calib data

### ISSUE THREAD

**Issue by metaselina** [fzhiheng/RoGS#4]
Hi, When I try to run the code, I see that there is no correct file for calib，and the link [https://s3.eu-central-1.amazonaws.com/avg-kitti/data_odometry_poses.zip](https://s3.eu-central-1.amazonaws.com/avg-kitti/data_odometry_poses.zip) is about odometry. When I downloaded the Kitti Odometry dataset, its calib file reads as follows:

![55a90673f1aeeed6a88a9a6f76baa6be](https://github.com/user-attachments/assets/5474420b-374f-46c4-9449-02bc8bba4a5c)

so, Can you provide the calib file that comes with the code?

**Comment by wolf943134497** [comment]
@fzhiheng  I encountered the same problem. I find the calib file in /KITTI/calib/000000.txt, but It is not a calibration file for kitti odometry，I can not get right results for "camera2world_all" when use the calib file, and the python train.py running error.

can you give some advice about kitti odometry calib file? Thanks

**Comment by fzhiheng** [comment]
![image](https://github.com/user-attachments/assets/6a8d3b4c-a6c9-4bc9-8ed6-4aaa583dc248)
The original calib file is from here. The purpose is simply to do a transformation from the camera pose to get the vehicle pose. The attached file can be used temporarily.
[000000.txt](https://github.com/user-attachments/files/16980094/000000.txt)

**Comment by wolf943134497** [comment]
@fzhiheng  Thanks for your rapid reply.  The code runs fine on kitti seq 00.
